version: '3.8'

services:
  perfex-db:
    image: mariadb:10.11
    container_name: perfex_db
    restart: always
    environment:
      - MYSQL_DATABASE=perfex
      - MYSQL_USER=perfex_user
      - MYSQL_PASSWORD=perfex_password_change_me
      - MYSQL_ROOT_PASSWORD=root_password_change_me
    volumes:
      - ./perfex-data/db:/var/lib/mysql
    networks:
      - pandanet_network

  perfex-app:
    image: php:8.2-apache
    container_name: perfex_app
    restart: always
    volumes:
      - ./perfex-data/app:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    networks:
      - pandanet_network
    depends_on:
      - perfex-db

networks:
  pandanet_network:
    name: pandanet_pandanet_network
    external: true
