import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'pt' | 'en' | 'es';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations = {
    pt: {
        'sidebar.home': 'Início',
        'sidebar.feed': 'Feed Social',
        'sidebar.messages': 'Mensagens',
        'sidebar.inbox': 'Caixa de Entrada',
        'sidebar.calendar': 'Calendário',
        'sidebar.marketplace': 'Marketplace',
        'sidebar.wellbeing': 'Bem-Estar',
        'sidebar.directory': 'Diretório',
        'sidebar.forms': 'Formulários',
        'sidebar.benefits': 'Benefícios',
        'sidebar.onboarding': 'Onboarding',
        'sidebar.recognition': 'Reconhecimento',
        'sidebar.documents': 'Documentos',
        'sidebar.ti_dashboard': 'Painel de T.I.',
        'sidebar.my_tickets': 'Meus Chamados',
        'sidebar.request_equipment': 'Solicitar Equipamento',
        'sidebar.admin': 'Admin',
        'sidebar.corporate_intranet': 'Intranet Corporativa',
        'sidebar.whatspanda': 'WhatsPanda',
        'sidebar.pandamail': 'PandaMail',
        'sidebar.events': 'Eventos',
        'sidebar.metrics': 'Métricas Grupo',
        'sidebar.rh_gestao': 'RH & Gestão',
        'sidebar.ti_suporte': 'T.I. & Suporte',
        'sidebar.org_chart': 'Organograma',
        'sidebar.meu_rh': 'Portal Meu RH',
        'sidebar.jobs': 'Portal de Vagas',
        'sidebar.surveys_internal': 'Pesquisas Internas',
        'sidebar.library': 'Biblioteca Corp.',
        'sidebar.user_manual': 'Manual do Usuário',
        'sidebar.saas_panel': 'Painel SaaS',
        'header.search_placeholder': 'Buscar...',
        'header.profile': 'Meu Perfil',
        'header.logout': 'Sair',
        'header.theme': 'Tema',
        'header.viewing_as': 'Você está visualizando a intranet da',
        'header.return_panel': 'Retornar ao Painel',
        'theme.light': 'Claro',
        'theme.dark': 'Escuro',
        'language.select': 'Idioma',
        'header.notifications_activate': 'Ativar Notificações',
        'header.notifications_choose_sound': 'Escolher Toque',
        'home.birthdays_title': 'Aniversariantes do Mês',
        'home.birthdays_none': 'Nenhum aniversário este mês.',
        'home.welcome_title': 'Boas-vindas!',
        'home.welcome_none': 'Nenhum novo colaborador recentemente.',

        // Modules
        'users.title': 'Gerenciar Usuários',
        'users.add': 'Adicionar Novo Usuário',
        'users.edit': 'Editar Usuário',
        'users.name': 'Nome',
        'users.email': 'Email',
        'users.password': 'Senha',
        'users.role': 'Cargo',
        'users.team': 'Equipe',
        'users.admin': 'É Administrador?',
        'users.sector_manager': 'Gestor do Setor',
        'users.employee_manager': 'Gerente do Funcionário',
        'users.permissions_feed': 'Permissões de Feed Social',
        'users.permissions_other': 'Outras Permissões',
        'users.save': 'Salvar Usuário',
        'users.cancel': 'Cancelar',
        'users.actions': 'Ações',
        'users.limit_reached': 'Limite de usuários atingido.',

        'forms.title': 'Central de Formulários',
        'forms.available': 'Formulários Disponíveis',
        'forms.my_requests': 'Minhas Solicitações',
        'forms.vacation': 'Solicitação de Férias',
        'forms.vacation_desc': 'Planeje e envie seu pedido de férias.',
        'forms.start_request': 'Iniciar Solicitação',
        'forms.reimbursement': 'Reembolso de Despesas',
        'forms.reimbursement_desc': 'Envie comprovantes para reembolso.',
        'forms.data_change': 'Alteração de Dados',
        'forms.data_change_desc': 'Atualize endereço, telefone, etc.',
        'forms.start_date': 'Data de Início',
        'forms.end_date': 'Data de Fim',
        'forms.reason': 'Motivo (Opcional)',
        'forms.submit': 'Enviar Solicitação',
        'forms.manager_sector': 'Gestor do Setor',
        'forms.manager_employee': 'Gerente Responsável',

        'training.title': 'Treinamentos e Desenvolvimento',
        'training.start': 'Iniciar Curso',
        'training.duration': 'Duração',

        'kb.title': 'Base de Conhecimento T.I.',
        'kb.search_placeholder': 'Como podemos ajudar? Pesquise por tutoriais, erros, acessos...',
        'kb.no_articles': 'Nenhum artigo encontrado.',

        'policies.title': 'Políticas e Diretrizes',
        'policies.download': 'Baixar',

        'status.title': 'Status dos Serviços',
        'status.overview': 'Visão Geral do Sistema',
        'status.all_operational': 'Todos os sistemas operacionais',
        'status.maintenance': 'Manutenção Programada',
        'status.operational': 'Operacional',
        'status.outage': 'Interrupção',
        'sidebar.training': 'Treinamentos',
        'sidebar.surveys': 'Pesquisas',
        'sidebar.infosec': 'Segurança da Info.',
        'sidebar.service_status': 'Status dos Serviços',
        'sidebar.knowledge_base': 'Base de Conhecimento',

        'generic.save': 'Salvar',
        'generic.cancel': 'Cancelar',
        'generic.delete_confirm': 'Tem certeza que deseja apagar este item?',
        'generic.new_item': 'Novo Item',
        'generic.edit_item': 'Editar Item',
        'email.write': 'Escrever',
        'email.new_folder': '+ Nova Pasta',
        'email.quick_tags': 'Tags rápidas',
        'email.no_emails': 'Nenhum e-mail encontrado.',
        'email.loading': 'Carregando...',
        'email.actions': 'Ações Rápidas',
        'email.read': 'Lido',
        'email.unread': 'Não Lido',
        'email.move_to': 'Mover para',
        'email.trash': 'Mover para Lixeira',
        'email.reply': 'Responder',
        'email.reply_all': 'Todos',
        'email.forward': 'Encaminhar',
        'email.delete': 'Excluir',
        'email.spam': 'Spam',
        'email.select_to_read': 'Selecione um e-mail para ler',
        'email.page': 'Página',
        'email.of': 'de',
        'email.previous': 'Anterior',
        'email.next': 'Próxima',
        'email.message': 'Mensagem',
        'email.new_message': 'Nova Mensagem',
        'email.settings': 'Configurações',
        'email.placeholder_to': 'Para:',
        'email.placeholder_subject': 'Assunto',
        'email.signature_warning': 'Sua assinatura será adicionada automaticamente.',
        'email.no_signature': 'Sem assinatura configurada.',
        'email.sending': 'Enviando...',
        'email.send': 'Enviar',
        'email.settings_title': 'Configurações de E-mail',
        'email.incoming_server': 'Servidor de Entrada (IMAP)',
        'email.host_imap': 'Host IMAP',
        'email.port': 'Porta',
        'email.user': 'Usuário',
        'email.pass': 'Senha do App',
        'email.use_ssl': 'Usar SSL/TLS',
        'email.outgoing_server': 'Servidor de Saída (SMTP)',
        'email.host_smtp': 'Host SMTP',
        'email.signature_title': 'Assinatura Automática',
        'email.signature_desc': 'Esta assinatura será adicionada ao final de todos os e-mails enviados.',
        'email.save_settings': 'Salvar Configurações',
        'email.manage_tags': 'Gerenciar Tags',
        'email.new_tag': 'Nova tag...',
        'email.no_tags': 'Nenhuma tag cadastrada',
        'email.close': 'Fechar',
        'email.loading_content': 'Carregando conteúdo...',
        'email.no_content': 'Sem conteúdo disponível ou falha ao carregar.',
        'email.attachments_title': 'Anexos',
        'email.download': 'Baixar',
        'email.add_tag': 'Adicionar Tag',
        'email.moved_spam': 'Movido para Spam',
        'email.no_preview': 'Sem pré-visualização...',
        'email.sent_folder': 'Enviados',
        'email.drafts_folder': 'Rascunhos',
        'email.trash_folder': 'Lixeira',
        'email.archive_folder': 'Arquivo',
        'email.outbox_folder': 'Caixa de Saída',
        'email.placeholder_search': 'Buscar e-mails...',
        'email.placeholder_tag_name': 'Nome da tag',
        'email.placeholder_compose': 'Escreva sua mensagem aqui...',

        // Calendar Placeholders
        'calendar.placeholder_title': 'Ex: Reunião de Planejamento',
        'calendar.placeholder_location': 'Ex: Sala A ou Google Meet',
        'calendar.placeholder_notes': 'Adicione observações importantes...',

        // Events Placeholders
        'events.placeholder_title': 'Ex: Treinamento de Integração',
        'events.placeholder_desc': 'Breve descrição do evento...',
        'events.placeholder_location': 'Ex: Sala de Reuniões A ou Zoom',
        'events.placeholder_image': 'https://...',
        'events.placeholder_reason': 'Motivo...',

        // TI Requests Placeholders
        'ti.placeholder_item': 'Ex: Teclado Mecânico, licença do Office...',
        'ti.placeholder_justification': 'Explique por que você precisa deste equipamento...',
        'ti.placeholder_comment': 'Digite seu comentário...',

        // Dashboard
        'dashboard.company_name': 'Nome da Empresa',
        'dashboard.domain': 'Domínio',
        'dashboard.cnpj': 'CNPJ',
        'dashboard.whatsapp': 'Whatsapp',
        'dashboard.responsible': 'Responsável',
        'dashboard.responsible_name': 'Nome do Responsável',
        'dashboard.responsible_email': 'Email do Responsável',
        'dashboard.total_users': 'Total de Usuários',
        'dashboard.online_users': 'Usuários Online',
        'dashboard.system_version': 'Versão do Sistema',
        'dashboard.registered_companies': 'Empresas Cadastradas',
        'dashboard.active_companies': 'Empresas Ativas',
        'dashboard.expired_companies': 'Empresas Vencidas',
        'dashboard.inactive_companies': 'Empresas Inativas',
        'dashboard.company_growth': 'Crescimento de Empresas',
        'dashboard.plan_distribution': 'Distribuição por Plano',
        'dashboard.announcements_title': 'Avisos Globais',
        'dashboard.settings_title': 'Configurações',
        'dashboard.dashboard_tab': 'DASHBOARD',
        'dashboard.companies_tab': 'EMPRESAS',
        'dashboard.plans_tab': 'PLANOS',
        'dashboard.announcements_tab': 'AVISOS GLOBAIS',
        'dashboard.settings_tab': 'CONFIGURAÇÕES',
        'dashboard.search_company': 'Localize empresa...',
        'dashboard.status_all': 'Status: todas',
        'dashboard.add_company': 'Adicionar',
        'dashboard.name': 'Nome',
        'dashboard.status': 'Status',
        'dashboard.users': 'Usuários',
        'dashboard.expiry': 'Vencimento',
        'dashboard.plan': 'Plano',
        'dashboard.actions': 'Ações',
        'dashboard.capacity': 'Capacidade:',
        'dashboard.users_plural': 'usuários',
        'dashboard.active_features': 'recursos ativos',
        'dashboard.investment': 'Investimento',
        'dashboard.post_update': 'Postar Atualização',
        'dashboard.system_logo': 'Logomarca do Sistema',
        'dashboard.no_logo_defined': 'Nenhuma logo definida',
        'dashboard.logo_selected': 'LOGO SELECIONADA',
        'dashboard.select_new_logo': 'SELECIONAR NOVA LOGO',
        'dashboard.logo_hint': '* Esta logo será exibida em todas as áreas que não possuem logo própria.',
        'dashboard.notification_duration': 'Manter Notificação Ativa Por:',
        'dashboard.hours': 'Horas',
        'dashboard.days': 'Dias',
        'dashboard.saving': 'SALVANDO...',
        'dashboard.save_settings': 'SALVAR CONFIGURAÇÕES',
        'dashboard.manual_videos': 'Vídeos do Manual',
        'dashboard.new_video': '+ Novo Vídeo',
        'dashboard.no_videos': 'Nenhum vídeo cadastrado.',
        'dashboard.version_history': 'Histórico de Versões',
        'dashboard.no_updates': 'Nenhuma atualização registrada.',

        // Calendar
        'calendar.title': 'Calendário',
        'calendar.subtitle': 'Gestão de eventos e compromissos',
        'calendar.new_event': 'Novo Evento',
        'calendar.year_view': 'VISÃO ANUAL',
        'calendar.month_view': 'VISÃO MENSAL',
        'calendar.schedule_event': 'Agendar Evento',
        'calendar.event_details': 'Preencha os detalhes do compromisso',
        'calendar.subject': 'Assunto',
        'calendar.date': 'Data',
        'calendar.category': 'Categoria',
        'calendar.private_event': 'Evento Privado',
        'calendar.private_desc': 'Este evento aparecerá somente para você no calendário.',
        'calendar.invite_team': 'Convidar Equipe/Departamento',
        'calendar.invite_users': 'Convidar Usuários',
        'calendar.cancel': 'CANCELAR',
        'calendar.save': 'SALVAR EVENTO',
        'calendar.back_year': 'Voltar para Visão Anual',
        'calendar.campaign': 'Campanha do Mês',
        'calendar.holidays': 'Feriados',
        'calendar.birthdays': 'Aniversários',
        'calendar.location': 'Localização',
        'calendar.notes': 'Observações',
        'calendar.attendees': 'Convidados',
        'calendar.rsvp_confirm': 'Confirmar',
        'calendar.rsvp_decline': 'Recusar',
        'calendar.decline_title': 'Recusar Convite',
        'calendar.decline_reason': 'Por favor, informe o motivo da recusa:',

        // Feed
        'feed.placeholder': 'O que está acontecendo na empresa?',
        'feed.post': 'Publicar',
        'feed.photo': 'Foto',
        'feed.recognize': 'Reconhecer',
        'feed.important': 'Importante: Postagens expiram automaticamente em 90 dias.',
        'feed.followers': 'Seguidores',
        'feed.users': 'Usuários',
        'feed.interactions': 'Interações',
        'feed.react': 'Reagir',
        'feed.comment': 'Comentar',
        'feed.share': 'Compartilhar',
        'feed.delete_post': 'Excluir postagem',
        'feed.delete_confirm': 'Tem certeza que deseja excluir esta postagem?',
        'feed.write_comment': 'Escreva um comentário...',
        'feed.people': 'Pessoas',
        'feed.online_now': 'Online Agora',
        'feed.suggestions': 'Sugestões de Colaboradores',
        'feed.discover_more': 'Descobrir Mais',

        // Months
        'month.0': 'Janeiro',
        'month.1': 'Fevereiro',
        'month.2': 'Março',
        'month.3': 'Abril',
        'month.4': 'Maio',
        'month.5': 'Junho',
        'month.6': 'Julho',
        'month.7': 'Agosto',
        'month.8': 'Setembro',
        'month.9': 'Outubro',
        'month.10': 'Novembro',
        'month.11': 'Dezembro',

        // Days
        'day.0': 'Dom',
        'day.1': 'Seg',
        'day.2': 'Ter',
        'day.3': 'Qua',
        'day.4': 'Qui',
        'day.5': 'Sex',
        'day.6': 'Sáb',
    },
    en: {
        'sidebar.home': 'Home',
        'sidebar.feed': 'Social Feed',
        'sidebar.messages': 'Messages',
        'sidebar.inbox': 'Inbox',
        'sidebar.calendar': 'Calendar',
        'sidebar.marketplace': 'Marketplace',
        'sidebar.wellbeing': 'Wellbeing',
        'sidebar.directory': 'Directory',
        'sidebar.forms': 'Forms',
        'sidebar.benefits': 'Benefits',
        'sidebar.onboarding': 'Onboarding',
        'sidebar.recognition': 'Recognition',
        'sidebar.documents': 'Documents',
        'sidebar.ti_dashboard': 'IT Dashboard',
        'sidebar.my_tickets': 'My Tickets',
        'sidebar.request_equipment': 'Request Equipment',
        'sidebar.admin': 'Admin',
        'sidebar.corporate_intranet': 'Corporate Intranet',
        'sidebar.whatspanda': 'WhatsPanda',
        'sidebar.pandamail': 'PandaMail',
        'sidebar.events': 'Events',
        'sidebar.metrics': 'Group Metrics',
        'sidebar.rh_gestao': 'HR & Management',
        'sidebar.ti_suporte': 'I.T. & Support',
        'sidebar.org_chart': 'Org Chart',
        'sidebar.meu_rh': 'My HR Portal',
        'sidebar.jobs': 'Job Portal',
        'sidebar.surveys_internal': 'Internal Surveys',
        'sidebar.library': 'Corp. Library',
        'sidebar.user_manual': 'User Manual',
        'sidebar.saas_panel': 'SaaS Panel',
        'header.search_placeholder': 'Search...',
        'header.profile': 'My Profile',
        'header.logout': 'Logout',
        'header.theme': 'Theme',
        'header.viewing_as': 'You are viewing the intranet of',
        'header.return_panel': 'Return to Panel',
        'theme.light': 'Light',
        'theme.dark': 'Dark',
        'language.select': 'Language',
        'header.notifications_activate': 'Activate Notifications',
        'header.notifications_choose_sound': 'Choose Sound',
        'home.birthdays_title': 'Birthdays of the Month',
        'home.birthdays_none': 'No birthdays this month.',
        'home.welcome_title': 'Welcome aboard!',
        'home.welcome_none': 'No new hires recently.',

        // Modules
        'users.title': 'Manage Users',
        'users.add': 'Add New User',
        'users.edit': 'Edit User',
        'users.name': 'Name',
        'users.email': 'Email',
        'users.password': 'Password',
        'users.role': 'Role',
        'users.team': 'Team',
        'users.admin': 'Is Admin?',
        'users.sector_manager': 'Sector Manager',
        'users.employee_manager': 'Employee Manager',
        'users.permissions_feed': 'Social Feed Permissions',
        'users.permissions_other': 'Other Permissions',
        'users.save': 'Save User',
        'users.cancel': 'Cancel',
        'users.actions': 'Actions',
        'users.limit_reached': 'User limit reached.',

        'forms.title': 'Forms Center',
        'forms.available': 'Available Forms',
        'forms.my_requests': 'My Requests',
        'forms.vacation': 'Vacation Request',
        'forms.vacation_desc': 'Plan and submit your vacation request.',
        'forms.start_request': 'Start Request',
        'forms.reimbursement': 'Expense Reimbursement',
        'forms.reimbursement_desc': 'Submit receipts for reimbursement.',
        'forms.data_change': 'Data Change',
        'forms.data_change_desc': 'Update address, phone, etc.',
        'forms.start_date': 'Start Date',
        'forms.end_date': 'End Date',
        'forms.reason': 'Reason (Optional)',
        'forms.submit': 'Submit Request',
        'forms.manager_sector': 'Sector Manager',
        'forms.manager_employee': 'Responsible Manager',

        'training.title': 'Training & Development',
        'training.start': 'Start Course',
        'training.duration': 'Duration',

        'kb.title': 'IT Knowledge Base',
        'kb.search_placeholder': 'How can we help? Search for tutorials, errors, access...',
        'kb.no_articles': 'No articles found.',

        'policies.title': 'Policies & Guidelines',
        'policies.download': 'Download',

        'status.title': 'Service Status',
        'status.overview': 'System Overview',
        'status.all_operational': 'All systems operational',
        'status.maintenance': 'Scheduled Maintenance',
        'status.operational': 'Operational',
        'status.outage': 'Outage',
        'sidebar.training': 'Training',
        'sidebar.surveys': 'Surveys',
        'sidebar.infosec': 'Info Security',
        'sidebar.service_status': 'Service Status',
        'sidebar.knowledge_base': 'Knowledge Base',

        'generic.save': 'Save',
        'generic.cancel': 'Cancel',
        'generic.delete_confirm': 'Are you sure you want to delete this item?',
        'generic.new_item': 'New Item',
        'generic.edit_item': 'Edit Item',
        'email.write': 'Write',
        'email.new_folder': '+ New Folder',
        'email.quick_tags': 'Quick Tags',
        'email.no_emails': 'No emails found.',
        'email.loading': 'Loading...',
        'email.actions': 'Quick Actions',
        'email.read': 'Read',
        'email.unread': 'Unread',
        'email.move_to': 'Move to',
        'email.trash': 'Move to Trash',
        'email.reply': 'Reply',
        'email.reply_all': 'Reply All',
        'email.forward': 'Forward',
        'email.delete': 'Delete',
        'email.spam': 'Spam',
        'email.select_to_read': 'Select an email to read',
        'email.page': 'Page',
        'email.of': 'of',
        'email.previous': 'Previous',
        'email.next': 'Next',
        'email.message': 'Message',
        'email.new_message': 'New Message',
        'email.settings': 'Settings',
        'email.placeholder_to': 'To:',
        'email.placeholder_subject': 'Subject',
        'email.signature_warning': 'Your signature will be added automatically.',
        'email.no_signature': 'No signature configured.',
        'email.sending': 'Sending...',
        'email.send': 'Send',
        'email.settings_title': 'Email Settings',
        'email.incoming_server': 'Incoming Server (IMAP)',
        'email.host_imap': 'IMAP Host',
        'email.port': 'Port',
        'email.user': 'User',
        'email.pass': 'App Password',
        'email.use_ssl': 'Use SSL/TLS',
        'email.outgoing_server': 'Outgoing Server (SMTP)',
        'email.host_smtp': 'SMTP Host',
        'email.signature_title': 'Automatic Signature',
        'email.signature_desc': 'This signature will be added to the end of all sent emails.',
        'email.save_settings': 'Save Settings',
        'email.manage_tags': 'Manage Tags',
        'email.new_tag': 'New tag...',
        'email.no_tags': 'No tags registered',
        'email.close': 'Close',
        'email.loading_content': 'Loading content...',
        'email.no_content': 'No content available or failed to load.',
        'email.attachments_title': 'Attachments',
        'email.download': 'Download',
        'email.add_tag': 'Add Tag',
        'email.moved_spam': 'Moved to Spam',
        'email.no_preview': 'No preview available...',
        'email.sent_folder': 'Sent',
        'email.drafts_folder': 'Drafts',
        'email.trash_folder': 'Trash',
        'email.archive_folder': 'Archive',
        'email.outbox_folder': 'Outbox',
        'email.placeholder_search': 'Search emails...',
        'email.placeholder_tag_name': 'Tag name',
        'email.placeholder_compose': 'Write your message here...',

        // Calendar Placeholders
        'calendar.placeholder_title': 'Ex: Planning Meeting',
        'calendar.placeholder_location': 'Ex: Room A or Google Meet',
        'calendar.placeholder_notes': 'Add important notes...',

        // Events Placeholders
        'events.placeholder_title': 'Ex: Integration Training',
        'events.placeholder_desc': 'Brief event description...',
        'events.placeholder_location': 'Ex: Meeting Room A or Zoom',
        'events.placeholder_image': 'https://...',
        'events.placeholder_reason': 'Reason...',

        // TI Requests Placeholders
        'ti.placeholder_item': 'Ex: Mechanical Keyboard, Office license...',
        'ti.placeholder_justification': 'Explain why you need this equipment...',
        'ti.placeholder_comment': 'Type your comment...',

        // Dashboard
        'dashboard.company_name': 'Company Name',
        'dashboard.domain': 'Domain',
        'dashboard.cnpj': 'ID Number',
        'dashboard.whatsapp': 'WhatsApp',
        'dashboard.responsible': 'Responsible',
        'dashboard.responsible_name': 'Responsible Name',
        'dashboard.responsible_email': 'Responsible Email',
        'dashboard.total_users': 'Total Users',
        'dashboard.online_users': 'Online Users',
        'dashboard.system_version': 'System Version',
        'dashboard.registered_companies': 'Registered Companies',
        'dashboard.active_companies': 'Active Companies',
        'dashboard.expired_companies': 'Expired Companies',
        'dashboard.inactive_companies': 'Inactive Companies',
        'dashboard.company_growth': 'Company Growth',
        'dashboard.plan_distribution': 'Plan Distribution',
        'dashboard.announcements_title': 'Global Announcements',
        'dashboard.settings_title': 'Settings',
        'dashboard.dashboard_tab': 'DASHBOARD',
        'dashboard.companies_tab': 'COMPANIES',
        'dashboard.plans_tab': 'PLANS',
        'dashboard.announcements_tab': 'GLOBAL ANNOUNCEMENTS',
        'dashboard.settings_tab': 'SETTINGS',
        'dashboard.search_company': 'Search company...',
        'dashboard.status_all': 'Status: all',
        'dashboard.add_company': 'Add',
        'dashboard.name': 'Name',
        'dashboard.status': 'Status',
        'dashboard.users': 'Users',
        'dashboard.expiry': 'Expiry',
        'dashboard.plan': 'Plan',
        'dashboard.actions': 'Actions',
        'dashboard.capacity': 'Capacity:',
        'dashboard.users_plural': 'users',
        'dashboard.active_features': 'active features',
        'dashboard.investment': 'Investment',
        'dashboard.post_update': 'Post Update',
        'dashboard.system_logo': 'System Logo',
        'dashboard.no_logo_defined': 'No logo defined',
        'dashboard.logo_selected': 'LOGO SELECTED',
        'dashboard.select_new_logo': 'SELECT NEW LOGO',
        'dashboard.logo_hint': '* This logo will be displayed in all areas that do not have their own logo.',
        'dashboard.notification_duration': 'Keep Notification Active For:',
        'dashboard.hours': 'Hours',
        'dashboard.days': 'Days',
        'dashboard.saving': 'SAVING...',
        'dashboard.save_settings': 'SAVE SETTINGS',
        'dashboard.manual_videos': 'Manual Videos',
        'dashboard.new_video': '+ New Video',
        'dashboard.no_videos': 'No videos registered.',
        'dashboard.version_history': 'Version History',
        'dashboard.no_updates': 'No updates registered.',

        // Calendar
        'calendar.title': 'Calendar',
        'calendar.subtitle': 'Event and appointment management',
        'calendar.new_event': 'New Event',
        'calendar.year_view': 'YEAR VIEW',
        'calendar.month_view': 'MONTH VIEW',
        'calendar.schedule_event': 'Schedule Event',
        'calendar.event_details': 'Fill in the appointment details',
        'calendar.subject': 'Subject',
        'calendar.date': 'Date',
        'calendar.category': 'Category',
        'calendar.private_event': 'Private Event',
        'calendar.private_desc': 'This event will only appear to you on the calendar.',
        'calendar.invite_team': 'Invite Team/Department',
        'calendar.invite_users': 'Invite Users',
        'calendar.cancel': 'CANCEL',
        'calendar.save': 'SAVE EVENT',
        'calendar.back_year': 'Back to Year View',
        'calendar.campaign': 'Campaign of the Month',
        'calendar.holidays': 'Holidays',
        'calendar.birthdays': 'Birthdays',
        'calendar.location': 'Location',
        'calendar.notes': 'Notes',
        'calendar.attendees': 'Attendees',
        'calendar.rsvp_confirm': 'Confirm',
        'calendar.rsvp_decline': 'Decline',
        'calendar.decline_title': 'Decline Invitation',
        'calendar.decline_reason': 'Please state the reason for declining:',

        // Feed
        'feed.placeholder': "What's happening at the company?",
        'feed.post': 'Post',
        'feed.photo': 'Photo',
        'feed.recognize': 'Recognize',
        'feed.important': 'Important: Posts expire automatically in 90 days.',
        'feed.followers': 'Followers',
        'feed.users': 'Users',
        'feed.interactions': 'Interactions',
        'feed.react': 'React',
        'feed.comment': 'Comment',
        'feed.share': 'Share',
        'feed.delete_post': 'Delete post',
        'feed.delete_confirm': 'Are you sure you want to delete this post?',
        'feed.write_comment': 'Write a comment...',
        'feed.people': 'People',
        'feed.online_now': 'Online Now',
        'feed.suggestions': 'Suggested Co-workers',
        'feed.discover_more': 'Discover More',

        // Months
        'month.0': 'January',
        'month.1': 'February',
        'month.2': 'March',
        'month.3': 'April',
        'month.4': 'May',
        'month.5': 'June',
        'month.6': 'July',
        'month.7': 'August',
        'month.8': 'September',
        'month.9': 'October',
        'month.10': 'November',
        'month.11': 'December',

        // Days
        'day.0': 'Sun',
        'day.1': 'Mon',
        'day.2': 'Tue',
        'day.3': 'Wed',
        'day.4': 'Thu',
        'day.5': 'Fri',
        'day.6': 'Sat',
    },
    es: {
        'sidebar.home': 'Inicio',
        'sidebar.feed': 'Feed Social',
        'sidebar.messages': 'Mensajes',
        'sidebar.calendar': 'Calendario',
        'sidebar.marketplace': 'Marketplace',
        'sidebar.wellbeing': 'Bienestar',
        'sidebar.directory': 'Directorio',
        'sidebar.forms': 'Formularios',
        'sidebar.benefits': 'Beneficios',
        'sidebar.onboarding': 'Onboarding',
        'sidebar.recognition': 'Reconocimiento',
        'sidebar.documents': 'Documentos',
        'sidebar.ti_dashboard': 'Panel de TI',
        'sidebar.my_tickets': 'Mis Tickets',
        'sidebar.request_equipment': 'Solicitar Equipo',
        'sidebar.admin': 'Admin',
        'sidebar.corporate_intranet': 'Intranet Corporativa',
        'sidebar.whatspanda': 'WhatsPanda',
        'sidebar.pandamail': 'PandaMail',
        'sidebar.events': 'Eventos',
        'sidebar.metrics': 'Métricas Grupo',
        'sidebar.rh_gestao': 'RR.HH. & Gestión',
        'sidebar.ti_suporte': 'T.I. & Soporte',
        'sidebar.org_chart': 'Organograma',
        'sidebar.meu_rh': 'Portal Mi RR.HH.',
        'sidebar.jobs': 'Portal de Empleos',
        'sidebar.surveys_internal': 'Encuestas Internas',
        'sidebar.library': 'Biblioteca Corp.',
        'sidebar.user_manual': 'Manual de Usuario',
        'sidebar.saas_panel': 'Panel SaaS',
        'header.search_placeholder': 'Buscar...',
        'header.profile': 'Mi Perfil',
        'header.logout': 'Salir',
        'header.theme': 'Tema',
        'header.viewing_as': 'Estás viendo la intranet de',
        'header.return_panel': 'Volver al Panel',
        'theme.light': 'Claro',
        'theme.dark': 'Escuro',
        'language.select': 'Idioma',
        'header.notifications_activate': 'Activar Notificaciones',
        'header.notifications_choose_sound': 'Elegir Tono',
        'home.birthdays_title': 'Cumpleaños del Mes',
        'home.birthdays_none': 'No hay cumpleaños este mes.',
        'home.welcome_title': '¡Bienvenidos!',
        'home.welcome_none': 'No hay nuevas contrataciones recientemente.',

        // Modules
        'users.title': 'Gestionar Usuarios',
        'users.add': 'Añadir Nuevo Usuario',
        'users.edit': 'Editar Usuario',
        'users.name': 'Nombre',
        'users.email': 'Correo',
        'users.password': 'Contraseña',
        'users.role': 'Cargo',
        'users.team': 'Equipo',
        'users.admin': '¿Es Administrador?',
        'users.sector_manager': 'Gestor del Sector',
        'users.employee_manager': 'Gerente del Empleado',
        'users.permissions_feed': 'Permisos de Feed Social',
        'users.permissions_other': 'Otros Permisos',
        'users.save': 'Guardar Usuario',
        'users.cancel': 'Cancelar',
        'users.actions': 'Acciones',
        'users.limit_reached': 'Límite de usuarios alcanzado.',

        'forms.title': 'Centro de Formularios',
        'forms.available': 'Formularios Disponibles',
        'forms.my_requests': 'Mis Solicitudes',
        'forms.vacation': 'Solicitud de Vacaciones',
        'forms.vacation_desc': 'Planifica y envía tu solicitud de vacaciones.',
        'forms.start_request': 'Iniciar Solicitud',
        'forms.reimbursement': 'Reembolso de Gastos',
        'forms.reimbursement_desc': 'Envía recibos para reembolso.',
        'forms.data_change': 'Cambio de Datos',
        'forms.data_change_desc': 'Actualiza dirección, teléfono, etc.',
        'forms.start_date': 'Fecha de Inicio',
        'forms.end_date': 'Fecha de Fin',
        'forms.reason': 'Motivo (Opcional)',
        'forms.submit': 'Enviar Solicitud',
        'forms.manager_sector': 'Gestor del Sector',
        'forms.manager_employee': 'Gerente Responsable',

        'training.title': 'Capacitación y Desarrollo',
        'training.start': 'Iniciar Curso',
        'training.duration': 'Duración',

        'kb.title': 'Base de Conocimientos TI',
        'kb.search_placeholder': '¿Cómo podemos ayudar? Busca tutoriales, errores, accesos...',
        'kb.no_articles': 'No se encontraron artículos.',

        'policies.title': 'Políticas y Directrices',
        'policies.download': 'Descargar',

        'status.title': 'Estado de los Servicios',
        'status.overview': 'Visión General del Sistema',
        'status.all_operational': 'Todos los sistemas operativos',
        'status.maintenance': 'Mantenimiento Programado',
        'status.operational': 'Operativo',
        'status.outage': 'Interrupción',
        'sidebar.training': 'Capacitación',
        'sidebar.surveys': 'Encuestas',
        'sidebar.infosec': 'Seguridad de Info.',
        'sidebar.service_status': 'Estado de Servicios',
        'sidebar.knowledge_base': 'Base de Conocimiento',

        'generic.save': 'Guardar',
        'generic.cancel': 'Cancelar',
        'generic.delete_confirm': '¿Estás seguro de que quieres eliminar este ítem?',
        'generic.new_item': 'Nuevo Ítem',
        'generic.edit_item': 'Editar Ítem',
        'email.write': 'Escribir',
        'email.new_folder': '+ Nueva Carpeta',
        'email.quick_tags': 'Etiquetas rápidas',
        'email.no_emails': 'No se encontraron correos.',
        'email.loading': 'Cargando...',
        'email.actions': 'Acciones Rápidas',
        'email.read': 'Leído',
        'email.unread': 'No Leído',
        'email.move_to': 'Mover a',
        'email.trash': 'Mover a Papelera',
        'email.reply': 'Responder',
        'email.reply_all': 'Todos',
        'email.forward': 'Reenviar',
        'email.delete': 'Eliminar',
        'email.spam': 'Spam',
        'email.select_to_read': 'Seleccione un correo para leer',
        'email.page': 'Página',
        'email.of': 'de',
        'email.previous': 'Anterior',
        'email.next': 'Siguiente',
        'email.message': 'Mensaje',
        'email.new_message': 'Nuevo Mensaje',
        'email.settings': 'Configuraciones',
        'email.placeholder_to': 'Para:',
        'email.placeholder_subject': 'Assunto',
        'email.signature_warning': 'Su firma se añadirá automáticamente.',
        'email.no_signature': 'Sin firma configurada.',
        'email.sending': 'Enviando...',
        'email.send': 'Enviar',
        'email.settings_title': 'Configuraciones de Correo',
        'email.incoming_server': 'Servidor de Entrada (IMAP)',
        'email.host_imap': 'Host IMAP',
        'email.port': 'Puerto',
        'email.user': 'Usuario',
        'email.pass': 'Contraseña de la App',
        'email.use_ssl': 'Usar SSL/TLS',
        'email.outgoing_server': 'Servidor de Saída (SMTP)',
        'email.host_smtp': 'Host SMTP',
        'email.signature_title': 'Firma Automática',
        'email.signature_desc': 'Esta firma se añadirá al final de todos los correos enviados.',
        'email.save_settings': 'Guardar Configuraciones',
        'email.manage_tags': 'Gestionar Etiquetas',
        'email.new_tag': 'Nueva etiqueta...',
        'email.no_tags': 'Ninguna etiqueta registrada',
        'email.close': 'Cerrar',
        'email.loading_content': 'Cargando contenido...',
        'email.no_content': 'Sin contenido disponible o fallo al cargar.',
        'email.attachments_title': 'Adjuntos',
        'email.download': 'Descargar',
        'email.add_tag': 'Añadir Etiqueta',
        'email.moved_spam': 'Movido a Spam',
        'email.no_preview': 'Sin vista previa...',
        'email.sent_folder': 'Enviados',
        'email.drafts_folder': 'Borradores',
        'email.trash_folder': 'Papelera',
        'email.archive_folder': 'Archivo',
        'email.outbox_folder': 'Bandeja de Salida',
        'email.placeholder_search': 'Buscar correos...',
        'email.placeholder_tag_name': 'Nombre de la etiqueta',
        'email.placeholder_compose': 'Escribe tu mensaje aquí...',

        // Calendar Placeholders
        'calendar.placeholder_title': 'Ej: Reunión de Planificación',
        'calendar.placeholder_location': 'Ej: Sala A o Google Meet',
        'calendar.placeholder_notes': 'Agregue notas importantes...',

        // Events Placeholders
        'events.placeholder_title': 'Ej: Entrenamiento de Integración',
        'events.placeholder_desc': 'Breve descripción del evento...',
        'events.placeholder_location': 'Ej: Sala de Reuniones A o Zoom',
        'events.placeholder_image': 'https://...',
        'events.placeholder_reason': 'Razón...',

        // TI Requests Placeholders
        'ti.placeholder_item': 'Ej: Teclado Mecânico, licencia de Office...',
        'ti.placeholder_justification': 'Explique por qué necesita este equipo...',
        'ti.placeholder_comment': 'Escriba su comentario...',

        // Dashboard
        'dashboard.company_name': 'Nombre de la Empresa',
        'dashboard.domain': 'Dominio',
        'dashboard.cnpj': 'NIF/CIF',
        'dashboard.whatsapp': 'WhatsApp',
        'dashboard.responsible': 'Responsable',
        'dashboard.responsible_name': 'Nombre del Responsable',
        'dashboard.responsible_email': 'Email del Responsable',
        'dashboard.total_users': 'Total de Usuarios',
        'dashboard.online_users': 'Usuarios en Línea',
        'dashboard.system_version': 'Versión del Sistema',
        'dashboard.registered_companies': 'Empresas Registradas',
        'dashboard.active_companies': 'Empresas Activas',
        'dashboard.expired_companies': 'Empresas Vencidas',
        'dashboard.inactive_companies': 'Empresas Inactivas',
        'dashboard.company_growth': 'Crecimiento de Empresas',
        'dashboard.plan_distribution': 'Distribución por Plan',
        'dashboard.announcements_title': 'Avisos Globales',
        'dashboard.settings_title': 'Configuraciones',
        'dashboard.dashboard_tab': 'INICIO',
        'dashboard.companies_tab': 'EMPRESAS',
        'dashboard.plans_tab': 'PLANES',
        'dashboard.announcements_tab': 'AVISOS GLOBALES',
        'dashboard.settings_tab': 'CONFIGURACIÓN',
        'dashboard.search_company': 'Buscar empresa...',
        'dashboard.status_all': 'Estado: todas',
        'dashboard.add_company': 'Añadir',
        'dashboard.name': 'Nombre',
        'dashboard.status': 'Estado',
        'dashboard.users': 'Usuarios',
        'dashboard.expiry': 'Vencimiento',
        'dashboard.plan': 'Plan',
        'dashboard.actions': 'Acciones',
        'dashboard.capacity': 'Capacidad:',
        'dashboard.users_plural': 'usuarios',
        'dashboard.active_features': 'recursos activos',
        'dashboard.investment': 'Inversión',
        'dashboard.post_update': 'Publicar Actualización',
        'dashboard.system_logo': 'Logo del Sistema',
        'dashboard.no_logo_defined': 'Sin logo definido',
        'dashboard.logo_selected': 'LOGO SELECCIONADA',
        'dashboard.select_new_logo': 'SELECCIONAR NUEVO LOGO',
        'dashboard.logo_hint': '* Este logo se mostrará en todas las áreas que no tengan logo propio.',
        'dashboard.notification_duration': 'Mantener Notificación Ativa Por:',
        'dashboard.hours': 'Horas',
        'dashboard.days': 'Días',
        'dashboard.saving': 'GUARDANDO...',
        'dashboard.save_settings': 'GUARDAR CONFIGURACIONES',
        'dashboard.manual_videos': 'Videos del Manual',
        'dashboard.new_video': '+ Nuevo Video',
        'dashboard.no_videos': 'Sin videos registrados.',
        'dashboard.version_history': 'Historial de Versiones',
        'dashboard.no_updates': 'Sin actualizaciones registradas.',

        // Calendar
        'calendar.title': 'Calendario',
        'calendar.subtitle': 'Gestión de eventos y citas',
        'calendar.new_event': 'Nuevo Evento',
        'calendar.year_view': 'VISTA ANUAL',
        'calendar.month_view': 'VISTA MENSUAL',
        'calendar.schedule_event': 'Programar Evento',
        'calendar.event_details': 'Complete los detalles de la cita',
        'calendar.subject': 'Asunto',
        'calendar.date': 'Fecha',
        'calendar.category': 'Categoría',
        'calendar.private_event': 'Evento Privado',
        'calendar.private_desc': 'Este evento solo te aparecerá a ti en el calendario.',
        'calendar.invite_team': 'Invitar Equipo/Departamento',
        'calendar.invite_users': 'Invitar Usuarios',
        'calendar.cancel': 'CANCELAR',
        'calendar.save': 'GUARDAR EVENTO',
        'calendar.back_year': 'Volver a la Vista Anual',
        'calendar.campaign': 'Campaña del Mes',
        'calendar.holidays': 'Feriados',
        'calendar.birthdays': 'Cumpleaños',
        'calendar.location': 'Ubicación',
        'calendar.notes': 'Notas',
        'calendar.attendees': 'Asistentes',
        'calendar.rsvp_confirm': 'Confirmar',
        'calendar.rsvp_decline': 'Rechazar',
        'calendar.decline_title': 'Rechazar Invitación',
        'calendar.decline_reason': 'Por favor, indique el motivo del rechazo:',

        // Feed
        'feed.placeholder': '¿Qué está pasando en la empresa?',
        'feed.post': 'Publicar',
        'feed.photo': 'Foto',
        'feed.recognize': 'Reconocer',
        'feed.important': 'Importante: Las publicaciones caducan automáticamente en 90 dias.',
        'feed.followers': 'Seguidores',
        'feed.users': 'Usuarios',
        'feed.interactions': 'Interacciones',
        'feed.react': 'Reaccionar',
        'feed.comment': 'Comentar',
        'feed.share': 'Compartir',
        'feed.delete_post': 'Eliminar publicación',
        'feed.delete_confirm': '¿Estás seguro de que quieres eliminar esta publicación?',
        'feed.write_comment': 'Escribe un comentario...',
        'feed.people': 'Personas',
        'feed.online_now': 'En línea ahora',
        'feed.suggestions': 'Sugerencias de compañeros',
        'feed.discover_more': 'Descubrir más',

        // Months
        'month.0': 'Enero',
        'month.1': 'Febrero',
        'month.2': 'Marzo',
        'month.3': 'Abril',
        'month.4': 'Mayo',
        'month.5': 'Junio',
        'month.6': 'Julio',
        'month.7': 'Agosto',
        'month.8': 'Septiembre',
        'month.9': 'Octubre',
        'month.10': 'Noviembre',
        'month.11': 'Diciembre',

        // Days
        'day.0': 'Dom',
        'day.1': 'Lun',
        'day.2': 'Mar',
        'day.3': 'Mié',
        'day.4': 'Jue',
        'day.5': 'Vie',
        'day.6': 'Sáb',
    }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguage] = useState<Language>(() => {
        if (typeof window !== 'undefined') {
            return (localStorage.getItem('language') as Language) || 'pt';
        }
        return 'pt';
    });

    useEffect(() => {
        localStorage.setItem('language', language);
    }, [language]);

    const t = (key: string): string => {
        // @ts-ignore
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
